
import pygame

FPS = 60
SCREEN_WIDTH = 280
SCREEN_HEIGHT = 610
GROUND_Y = 500
PIPE_HEIGHT = 320
MIN_PIPE_GAP = 150
MAX_GRAVITY = 9.8
ALL_PIPE_VARIANTS = ['green', 'red']
MAX_LEVEL = 7
SCORE_PER_LEVEL = 1
ALLOWED_KEYS = [pygame.K_SPACE, pygame.K_UP]
