FPS = 60
SCREEN_WIDTH = 280
# SCREEN_WIDTH = 500
SCREEN_HEIGHT = 610
GROUND_Y = 500
PIPE_HEIGHT = 320
MIN_PIPE_GAP = 150
MAX_GRAVITY = 9.8


ALL_BIRD_COLORS = ['red', 'yellow', 'blue']
ALL_FLAP_VARIANTS = ['down', 'mid', 'up']
ALL_PIPE_VARIANTS = ['green', 'red']
MAX_LEVEL = 7
SCORE_PER_LEVEL = 5
